Написан код для задачи 1-1
Despair-111/DmitriyPotkin pull request #4
Opened 2021-03-21 21:50 UTC by Despair-111

2021-03-21 22:46 UTC, Const-Phi commented
Хоть Вы и не просили меня о проведении рецензирования данного PR, но Вам _необходимо_ добавить правильно сформированный файл `.gitignore`, так как в Вашем PR полно мусора &ndash; `*.suo`, `*.exe`, `.vs/*` etc. Ваш файл `.gitignore` сформирован не вполне корректно, так как Вы игнорируете &laquo;продукты жизнедеятельности&raquo; _только_ `microsoftoffice` и `latex`. Не знаю собираетесь ли Вы верстать при помощи [LaTeX](https://ru.wikipedia.org/wiki/LaTeX) и знаете ли что это, но про [Visual Studio](https://visualstudio.microsoft.com/ru/vs/) Вы точно позабыли.

![image](https://user-images.githubusercontent.com/8349213/111923348-c55c4300-8aaf-11eb-8f5a-c53852ef651c.png)

`.gitignore`, сформированный более подходящим образом, можно скачать [здесь](https://www.toptal.com/developers/gitignore/api/windows,microsoftoffice,visualstudio). Или стоит отредактировать уже существующий с учётом замечаний. Так или иначе, но [Марина Алексеевна](https://miit.ru/people/8471) начнёт непосредственно с этого же момента, так как проверять 23 файла вместо (примерно) 5, из которых целевой только один &ndash; мало приятное удовольствие.

2021-03-21 23:03 UTC, Const-Phi requested changes
Вам стоит учесть все замечания.

После внесения изменений в Ваш локальный репозиторий оформите подобающим образом коммит и отправьте (`push`) его в ветку, связанную с данным PR-ом (`origin/featrue/1`). После чего перезапросите ревью у меня или Марины Алексеевны.

Все подробности работы по процессу освещены в &laquo;методичке&raquo; в картинках. Она должна быть доступна в учебных материалах Вашей группы (в MS Teams).

2021-03-21 23:03 UTC, Const-Phi commented on Work 1-1/тест/тест.cpp
> +
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Зачем все эти пустые строки?

2021-03-21 23:03 UTC, Const-Phi commented on Work 1-1/тест/тест.cpp
> +
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Здесь и далее после документирующего комментария избыточная пустая строка.

2021-03-21 23:03 UTC, Const-Phi commented on Work 1-1/тест/тест.cpp
> +{
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Отсутствует документирующий комментарий и избыточная пустая строка между сигнатурой функции и её телом.

2021-03-27 19:43 UTC, Const-Phi requested changes
За исправленный `.gitignore` и выброшенный мусор плюс в карму. 

Но всё же стоит вносить изменения _осмысленно_. Человек, даже не умеющий программировать, просто исходя из опыта общения с текстом, в состоянии интуитивно понять какое изменение облегчит его (текста) восприятие, а какое &ndash; затруднит. Ваши же правки порою контринтуитивны, и я затрудняюсь сказать, что Вами руководило в момент принятия данного решения.

2021-03-27 19:43 UTC, Const-Phi commented on Код задачи 1-1.cpp
> +
Вы издеваетесь? Или Вы не владеете в достаточной мере русским языком? (Как альтернативу могу предложить английский или _русский матерный_)

Верните те пустые строки, что вы убрали &ndash; _вот они-то как раз нужны_ и уберите _эти_! Зачем Вам 10 (_десять!_) пустых строк после вашей функции `main`?!

2021-04-02 20:28 UTC, MarinaPaley requested changes

2021-04-02 20:28 UTC, MarinaPaley commented on Task 1-1.cpp
> +    cout << "x=" << x << ", y=" << y << ", z=" << z << "\n";
оставляйте пробелы, так удобнее читать `x = `

2021-04-02 20:28 UTC, MarinaPaley commented on Task 1-1.cpp
> +double getA(double x, double y, double z)
Здесь пишут только заголовок функции, реализация идет отдельно.

2021-04-03 09:33 UTC, MarinaPaley requested changes

2021-04-03 09:33 UTC, MarinaPaley commented on Task 1-1.cpp
> +    const auto a = getA(x, y, z);
рука дернулась? выравнивание нужно соблюдать. Python на Вас не хватает!!!

2021-04-03 09:33 UTC, MarinaPaley commented on Task 1-1.cpp
> +	cout << "a = " << a << ", b = " << b;
рука дернулась? выравнивание нужно соблюдать. Python на Вас не хватает!!!

2021-04-03 09:33 UTC, MarinaPaley commented on Task 1-1.cpp
> +double getA(double x, double y, double z)
`const` необъодимо явно писать. Это язык C++, очень важно.

2021-04-03 18:37 UTC, MarinaPaley approved these changes

2021-04-05 16:01 UTC, merged